# Cloudflare Worker Configuration - PIR Guards Executor

name = "pir-guards-executor"
main = "src/index.ts"
compatibility_date = "2024-03-01"
workers_dev = true

# Account ID
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"

# Workers AI binding
[ai]
binding = "AI"

# Environment variables
[vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"

# Limites
[limits]
cpu_ms = 50000  # Guards executam em paralelo
